### ISSUE TITLE
Pagination not working??

### ISSUE THREAD

**Issue by pulketo** [jacklenox/susty#7] opened 2018-07-27 15:29 UTC
Pagination is not working :( 
404 issued instead

**Comment by jacklenox** [comment] 2018-08-11 15:54
Hi @pulketo, can you provide more info here? I haven't noticed any issues with pagination. Can you let me know what URL isn't working, and have you checked it's definitely the theme and not how you have WordPress configured e.g. check that pagination definitely is working with the default theme.

**Comment by jacklenox** [comment] 2018-09-14 17:40
No news, and I can't reproduce, so I'm closing this.

**Closed as completed by jacklenox** 2018-09-14 17:40 UTC
Labels: question
